### ISSUE TITLE
bug: ingest-processor chown -R abc:abc /calibre-library fails on NFS mounts (regression since PR #1349)

### ISSUE THREAD

**Issue by standhaftsohnsergius** [crocodilestick/Calibre-Web-Automated#1451]
## Summary

Since the ingest processor rewrite in PR #1349 (merged 2026-07-05), the ingest pipeline runs `chown -R abc:abc /calibre-library` after every import. This call unconditionally fails when `/calibre-library` is on an NFS mount, breaking the lock-file mechanism and causing instability in the ingest pipeline.

This is a regression — the same setup worked correctly before the PR #1349 update.

## Environment

- **CWA image:** `crocodilestick/CalibreWebAutomated:latest` (pulled after 2026-07-05)
- **Deployment:** Docker inside a privileged LXC container (Proxmox/Debian 12)
- **Storage:** `/calibre-library` and `/cwa-book-ingest` are NFS bind-mounts from TrueNAS SCALE
- **NFS version:** v4.1
- **File owner on NFS:** UID 3010 / GID 3010 (`books` user)
- **Container user:** `abc` = UID 911 / GID 911 (linuxserver.io default, `PUID`/`PGID` env vars are silently ignored by this image)

## Observed behavior in logs

```
chown: changing ownership of '/calibre-library/Some Author/Some Book/book.pdf': Operation not permitted
[ingest-processor] An error occurred while attempting to recursively set ownership of /calibre-library to abc:abc. See the following error:
Command '["chown", "-R", "abc:abc", "/calibre-library"]' returned non-zero exit status 1.
[ingest-processor] Lock file contains invalid PID, treating as stale
[ingest-processor] Cleaned up stale lock file: /tmp/ingest_processor.lock
[ingest-processor] Error acquiring lock: 'NoneType' object has no attribute 'fileno'
[library-refresh] The book ingest service is already running ✋ Please wait until it has finished before trying again ⌛
```

The `chown` error corrupts the lock-file state, causing subsequent ingest runs to either deadlock or skip processing entirely.

## Root cause

NFS does not allow `chown` on files the caller does not own — even when the NFS export has `Maproot` set. The `chown -R abc:abc /calibre-library` call introduced in PR #1349 hits every file in the entire library on every import, which:
1. Always fails on NFS (regardless of permissions setup)
2. Leaves the lock-file in a broken state (`fileno` error on `None`)
3. Was not present in the codebase before PR #1349

## Expected behavior

The `chown` call should either:
- Be skipped when the volume is a network filesystem (NFS/CIFS), or
- Be wrapped in a try/except that logs a warning and continues gracefully instead of corrupting the lock state, or
- Only run during container init (s6-overlay init phase), not after every single import

## Workaround (for others hitting this)

Create a user `abc` with UID 911 on the NAS and set it as owner/group of the library files, so the `chown` call succeeds:

```bash
# On NAS host:
groupadd -g 911 abc
useradd -u 911 -g 911 abc
chown -R 911:911 /path/to/calibre-library
```

Or set NFS Maproot to UID 911 for the CWA container's IP.

## Additional context

The lock-file corruption caused by the failed `chown` is the more serious secondary bug — the ingest processor should handle a failed `chown` gracefully and not let it invalidate the PID lock. Even if fixing NFS `chown` is out of scope, the lock state should be resilient to this error.
