### ISSUE TITLE
[bug] AttributeError: '_MinimalConfig' object has no attribute 'config_books_per_page'` on v4.0.1

### ISSUE THREAD

**Issue by sillmnvg** [crocodilestick/Calibre-Web-Automated#961]
**Describe the bug**
App fails to load upon login with below error on v4.0.1

**To Reproduce**
1. recreate container with latest v4.0.1 tag

**Expected behavior**
App should load upon upgrading to new version.

**Configuration(please complete the following information):**

    OS: Ubuntu 25.04
    Hardware: x86
    Version 4.0.0

**Additional context**
Traceback:

`Traceback (most recent call last):
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/usermanagement.py", line 181, in decorated_view
return login_required(func)(*args, **kwargs)
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/cw_login/utils.py", line 318, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/web.py", line 1017, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web-automated/cps/web.py", line 475, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
True, config.config_read_column,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
db.books_series_link,
^^^^^^^^^^^^^^^^^^^^^
db.Books.id == db.books_series_link.c.book,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
db.Series)
^^^^^^^^^^
File "/app/calibre-web-automated/cps/db.py", line 976, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
join_archive_read, config_read_column, *join, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/db.py", line 983, in fill_indexpage_with_archived_books
pagesize = pagesize or self.config.config_books_per_page
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_MinimalConfig' object has no attribute 'config_books_per_page'`

**Comment by crocodilestick** [comment]
Found the issue, fix coming in v4.0.2 tonight

**Comment by sillmnvg** [comment]
> Found the issue, fix coming in v4.0.2 tonight

Man you are AWESOME.

**Comment by crocodilestick** [comment]
Fixed as of v4.0.2

**Comment by sillmnvg** [comment]
Unfortunately still getting a 500 even after updating to v4.0.2:
``Traceback (most recent call last):
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/usermanagement.py", line 181, in decorated_view
return login_required(func)(*args, **kwargs)
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/cw_login/utils.py", line 318, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/web.py", line 1017, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web-automated/cps/web.py", line 475, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
True, config.config_read_column,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
db.books_series_link,
^^^^^^^^^^^^^^^^^^^^^
db.Books.id == db.books_series_link.c.book,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
db.Series)
^^^^^^^^^^
File "/app/calibre-web-automated/cps/db.py", line 997, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
join_archive_read, config_read_column, *join, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/db.py", line 1016, in fill_indexpage_with_archived_books
query = self.generate_linked_query(config_read_column, database)
File "/app/calibre-web-automated/cps/db.py", line 957, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'query'
